name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    
    - uses: actions/setup-node@v3
      with: 
        cache: 'npm'
        
    - name: Run Setup
      run: make setup
      
    - name: Run Test
      run: make test
      
    - name: Run Lint
      run: make lint
